# Maintainer Name
OF_MAINTAINER := "Mod4"

# partition settings
OF_FORCE_PREBUILT_KERNEL := 1
OF_ENABLE_LPTOOLS := 1
OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_ENABLE_FRP_ADDON := 1
OF_USE_DMCTL := 1
OF_ENABLE_FASTBOOTD := 1
OF_PATCH_AVB20 := 1
OF_ENABLE_FS_COMPRESSION := 1

# gui settings
OF_STATUS_INDENT_RIGHT := 80
OF_STATUS_INDENT_LEFT := 80
OF_OPTIONS_LIST_NUM := 8
OF_SCREEN_H := 2400
OF_USE_GREEN_LED := 0
OF_HIDE_NOTCH := 1
OF_STATUS_H := 122
OF_CLOCK_POS := 1
OF_USE_LOCKSCREEN_BUTTON := 1
OF_SPLASH_MAX_SIZE := 130

# legacy battery
OF_USE_LEGACY_BATTERY_SERVICES := 1

# Enable the flashlight
OF_FLASHLIGHT_ENABLE := 1

# Extra Features
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
